galaxy_info:
  role_name: "hostname"
  namespace: genlab
  author: "Alexander Gorelyhsev"
  description: "Set the hostname of the node"
  company: "GenLab LLC"
  license: "BSD"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["focal", "jammy", "noble"]

  galaxy_tags: []

dependencies: []
