---
- name: "Create | update a Grafana user"
  no_log: "{{ grafana_no_log }}"
  community.grafana.grafana_user:
    url: "http://127.0.0.1:{{ grafana_port }}"
    url_username: "{{ grafana_admin_api_username }}"
    url_password: "{{ grafana_admin_api_password }}"
    name: "{{ user.name }}"
    email: "{{ user.user_email }}"
    login: "{{ user.user_login }}"
    password: "{{ user.user_password }}"
    is_admin: "{{ user.is_admin | default(false) }}"
    state: present
