---
galaxy_info:
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: "Deploy czerwonk/ping_exporter as a systemd unit"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["focal"]

  galaxy_tags: ["prometheus"]

dependencies: []
