---
- name: Converge for slurm database daemon
  hosts: all
  vars:
    mysql_port: "3306"
    mysql_root_password: "test_molecule"
    mysql_databases:
      - name: slurm_acct_db
        encoding: utf8mb4
        collation: utf8mb4_general_ci
    mysql_users:
      - name: slurm
        host: "%"
        password: "test_molecule"
        priv: "slurm_acct_db.*:ALL"
    mysql_bind_address: "0.0.0.0"
    slurm_roles: ['dbd', "controller"]
    slurmdbd_cluster_name: test-cluster
    __slurmdbd_config_default:
      AuthType: auth/munge
      DbdHost: localhost
      DbdPort: 6819
      SlurmUser: slurm
      LogFile: /var/log/slurm/slurmdbd.log
      PidFile: /run/slurm/slurmdbd.pid
      StorageType: accounting_storage/mysql
      StorageHost: localhost
      StoragePort: 3306
      StorageUser: slurm
      StoragePass: "test_molecule"
      StorageLoc: slurm_acct_db
      MessageTimeout: 60
      PrivateData: accounts,users,jobs
      DebugLevel: info
    slurm_config:
      ClusterName: "{{ slurmdbd_cluster_name  }}"
      SlurmctldHost: localhost
      AuthType: auth/munge
      AccountingStorageType: accounting_storage/slurmdbd
      AccountingStorageHost: localhost
      AccountingStoragePort: 6819
    slurm_create_user: true
    slurm_accounts:
      - account_name: test
        account_description: "molecule test account"
        account_organization: molecule

  pre_tasks:
    - name: Install MySQL dev libraries (Ubuntu)
      ansible.builtin.apt:
        name: libmysqlclient-dev
        state: present
        update_cache: true

  roles:
    - role: geerlingguy.mysql

    - role: genlab.common.slurm
