---
galaxy_info:
  role_name: "win_wg_spoke"
  namespace: genlab
  author: "Sergey Malyuk"
  company: "Genlab, LLC"
  description: "Configures wireguard spoke on windows"
  license: "MIT"
  min_ansible_version: "2.16"

  platforms:
    - name: "Windows"

  galaxy_tags: []

dependencies: []
