---
- name: Install agent configuration
  ansible.builtin.template:
    src: agent.ini.j2
    dest: /etc/slurm-web/agent.ini
    owner: "{{ slurm_web_user }}"
    group: "{{ slurm_web_group }}"
    mode: "0640"
  notify: Restart slurm-web-agent

- name: Install policy configuration
  ansible.builtin.template:
    src: policy.ini.j2
    dest: /etc/slurm-web/policy.ini
    owner: "{{ slurm_web_user }}"
    group: "{{ slurm_web_group }}"
    mode: "0640"
  notify: Restart slurm-web-agent
