---
namespace: genlab
name: common
version: 0.32.0
readme: README.md
authors:
  - Alexander Gorelyshev (corvus-migratorius@proton.me)
  - Sergey Malyuk (malyuk.ss@genlab.llc)
description: >-
  The genlab.common collection includes roles for performing deploying and configuring common infrastructural components
license_file: LICENSE
tags:
  - linux
  - infrastructure
  - genlab
repository: https://github.com/corvus-migratorius/genlab.common
issues: https://github.com/corvus-migratorius/genlab.common/issues
