---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.grafana
  - name: community.docker
  - name: community.crypto
  - name: maxhoesel.borgbackup
  - name: lucasheld.uptime_kuma
  - name: community.postgresql
