---
- name: "Install role dependencies on Debian/Ubuntu"
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: [acl, unzip]
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Install role dependencies on RedHat/CentOS"
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name: [acl, unzip]
    state: present
    update_cache: true

- name: "Create the 'promtail' user"
  ansible.builtin.user:
    name: promtail
    groups:
      - adm
      - systemd-journal
    shell: /bin/nologin
    home: /var/lib/promtail
    state: present
    system: true

- name: "Set facl to allow promtail user to read all '/var/log' contents"
  ansible.posix.acl:
    path: /var/log
    entity: promtail
    etype: user
    permissions: rX
    state: present

- name: "Make promtail user owner of '{{ promtail_positions_path }}'"
  changed_when: false
  ansible.builtin.file:
    path: "{{ promtail_positions_path }}"
    owner: promtail
    group: promtail
    state: touch
    mode: "0750"

- name: "Read installed Promtail version"
  register: promtail_version_check
  changed_when: false
  failed_when: false
  ansible.builtin.command:
    argv:
      - "{{ promtail_binary_path }}"
      - "-version"

- name: "Set Promtail installation requirement"
  ansible.builtin.set_fact:
    promtail_install_required: >-
      {{
        promtail_version_check.rc != 0
        or promtail_version not in promtail_version_check.stdout
      }}

- name: "Install requested Promtail version"
  when: promtail_install_required
  block:
    - name: "Install Promtail {{ promtail_version }}"
      notify: "Enable and restart the Promtail daemon"
      retries: 3
      delay: 3
      ansible.builtin.unarchive:
        src: "https://github.com/grafana/loki/releases/download/v\
             {{ promtail_version }}/promtail-linux-amd64.zip"
        dest: "{{ promtail_installation_path }}"
        remote_src: true

    - name: "Rename and set permissions for the Promtail binary"
      ansible.builtin.copy:
        src: "{{ promtail_installation_path }}/promtail-linux-amd64"
        dest: "{{ promtail_installation_path }}/promtail"
        owner: root
        group: root
        mode: "0750"
        remote_src: true

    - name: "Cleanup the downloaded file"
      ansible.builtin.file:
        path: "{{ promtail_installation_path }}/promtail-linux-amd64"
        state: absent

- name: "Template the systemd unit file"
  notify: "Enable and restart the Promtail daemon"
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
    owner: root
    group: root
    mode: "0640"

- name: "Ensure '/etc/promtail' exists"
  ansible.builtin.file:
    path: /etc/promtail
    state: directory
    owner: promtail
    group: promtail
    mode: "0750"

- name: "Template Promtail config file"
  notify: "Enable and restart the Promtail daemon"
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: /etc/promtail/config.yml
    owner: root
    group: root
    mode: "0640"

- name: "Ensure the Promatail service is enabled and running"
  ansible.builtin.systemd_service:
    name: promtail
    state: started
    enabled: true
    daemon_reload: true
