---
- name: "Restart the ssh service"
  listen: "Restart ssh"
  when: ansible_os_family == 'Debian'
  ansible.builtin.service:
    name: ssh
    state: restarted
    enabled: true
    daemon_reload: true

- name: "Restart the sshd service"
  listen: "Restart ssh"
  when: ansible_os_family == 'RedHat'
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: true
    daemon_reload: true
