---
- name: Converge
  hosts: all
  vars:
    slurm_roles: ['controller', 'exec', 'dbd']
    slurm_create_user: true
    slurm_cgroup_config:
      CgroupPlugin: autodetect
      ConstrainCores: yes
      ConstrainDevices: yes
    slurm_munge_key: /home/mariia/proxmox-terraform/munge.key
    slurm_config:
      AccountingStorageType: accounting_storage/slurmdbd

  pre_tasks:
    - name: Install MariaDB packages
      become: true
      ansible.builtin.apt:
        name:
        - python3-mysqldb
        - python3-pymysql
        - mariadb-server
        - mariadb-client
        - mariadb-backup
        state: present
        update_cache: true

    - name: Enable and start MariaDB
      become: true
      ansible.builtin.systemd:
        name: mariadb
        enabled: true
        state: started

    - name: Bootstrap MariaDB root password
      become: true
      ansible.builtin.shell: |
        mysql -u root <<EOF
        ALTER USER 'root'@'localhost' IDENTIFIED BY 'molecule_test';
        FLUSH PRIVILEGES;
        EOF
      args:
        executable: /bin/bash
      register: mysql_bootstrap
      failed_when: false
      changed_when: "'ALTER USER' in mysql_bootstrap.stdout"

    - name: Create .my.cnf for root
      become: true
      ansible.builtin.copy:
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: '0600'
        content: |
          [client]
          user=root
          password=molecule_test

  roles:
    - role: genlab.slurm
      become: true
