---
- name: Verify Slurm installation
  hosts: all
  become: true

  pre_tasks:
    - name: Load role default variables
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/../../defaults"

  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Assert all slurm services are running
      ansible.builtin.assert:
        that: ansible_facts.services[item].state == 'running'
        fail_msg: "{{ item }} is not running"
      loop:
        - munge.service
        - slurmctld.service

    - name: Check slurmctld is responsive
      ansible.builtin.command: scontrol ping
      changed_when: false
      register: scontrol_ping

    - name: Assert slurmctld responded
      ansible.builtin.assert:
        that: "'UP' in scontrol_ping.stdout"
        fail_msg: "{{ scontrol_ping.stdout }}"

    - name: Check openmetrics endpoint
      ansible.builtin.uri:
        url: "http://localhost:{{ __slurm_config_default.SlurmctldPort }}/metrics/nodes"
        method: GET
        status_code: 200
        return_content: true
      register: metrics

    - name: Assert cluster metrics are present
      ansible.builtin.assert:
        that:
          - "'slurm_node_cpus' in metrics.content"
          - "'slurm_nodes_idle' in metrics.content"
        fail_msg: "openmetrics endpoint did not return expected metrics"
