---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # https://github.com/ansible/molecule/issues/3587#issuecomment-1158650179
    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: ['yml']

    # kics-scan ignore-block - HTTP
    - name: "Sanity check the Promtail daemon"
      retries: 60
      delay: 1
      register: promtail_readiness
      # failed_when: "promtail_this.content != 'Ready'"
      until:
        - (promtail_readiness.status | default(-1)) == 200
        - (promtail_readiness.content | default("")) == "Ready"
      ansible.builtin.uri:
        url: "http://localhost:{{ promtail_http_port }}/ready"
        return_content: true
        method: GET
        status_code: 200
