---
argument_specs:
  main:
    description: "Deploy a lean Fail2Ban sshd configuration"
    options:
      fail2ban_sshd_version:
        type: str
      fail2ban_sshd_jail_enabled:
        type: bool
      fail2ban_sshd_jail_port:
        type: str
      fail2ban_sshd_jail_findtime:
        type: int
      fail2ban_sshd_jail_maxretry:
        type: int
      fail2ban_sshd_jail_bantime:
        type: int
      fail2ban_sshd_jail_logpath:
        type: str
      fail2ban_sshd_jail_backend:
        type: str
      fail2ban_sshd_jail_banaction:
        type: str
      fail2ban_sshd_jail_ignoreips:
        type: list
