---
miniforge_release: 24.3.0-0
miniforge_script_path: "/tmp/{{ miniforge_install_script_name }}.sh"
miniforge_release_base_url: "https://github.com/conda-forge/miniforge/releases/download/"
miniforge_create_envs: false
