---
- name: Create slurm group
  ansible.builtin.group:
    name: "{{ slurm_group_name }}"
    gid: "{{ slurm_user_gid }}"
    system: true

- name: Create slurm user
  ansible.builtin.user:
    name: "{{ slurm_user_name }}"
    comment: "slurm system user"
    uid: "{{ slurm_user_uid }}"
    group: "{{ slurm_group_name }}"
    create_home: false
    shell: /bin/false
    system: true
