---
- name: Converge
  hosts: all
  vars:
    slurm_roles: ['controller', 'exec']
    slurm_create_user: true
    slurm_cgroup_config:
      CgroupPlugin: autodetect
      ConstrainCores: yes
      ConstrainDevices: yes
    slurm_munge_key: /home/mariia/proxmox-terraform/munge.key
    slurm_config:
      SlurmctldHost: localhost
      SlurmctldPidFile: /var/run/slurmctld.pid
      SlurmdPidFile: /var/run/slurmd.pid
      SlurmctldLogFile: /var/log/slurm/slurmctld.log
      SlurmdLogFile: /var/log/slurm/slurmd.log
      SlurmctldDebug: debug5
      SlurmdDebug: debug5
      SlurmctldPort: 6817
      SlurmdPort: 6818
      JobAcctGatherType: jobacct_gather/linux
      JobAcctGatherFrequency: 30
      SelectType: select/cons_tres
      SelectTypeParameters: CR_CPU_Memory,CR_CORE_DEFAULT_DIST_BLOCK
      SchedulerType: sched/backfill
      ProctrackType: proctrack/cgroup
      TaskPlugin: task/cgroup
      PropagateResourceLimitsExcept: MEMLOCK
      SchedulerParameters: bf_continue
      DefMemPerCPU: 4000
      SlurmctldTimeout: 300
      SlurmdTimeout: 300
 
  roles:
    - role: genlab.slurm
      become: true
