---
- name: "Install | Create alertmanager system user"
  ansible.builtin.user:
    name: "alertmanager"
    system: true
    shell: "/sbin/nologin"
    create_home: false
    state: present

- name: "Install | Create directories"
  loop:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_storage_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "alertmanager"
    group: "alertmanager"
    mode: "0755"

- name: "Install | Install the binaries"
  block:
    - name: "Install | Check alertmanager version"
      changed_when: false
      register: alertmanager_ver
      ansible.builtin.command:
        cmd: "alertmanager --version"

    - name: "Install | Assert version correctness"
      ansible.builtin.assert:
        that: "alertmanager_ver.stdout is regex('{{ alertmanager_version }}')"
        success_msg: "alertmanager version {{ alertmanager_version }} is installed and working"
        fail_msg: "alertmanager version {{ alertmanager_version }} is not installed or not working correctly"

  rescue:
    - name: "Install | Fetch and unpack the distribution"
      notify: "(Re)start and enable Alertmanager"
      retries: 3
      delay: 3
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/\
              alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64"
        remote_src: true

    - name: "Install | Put the binaries under the PATH"
      loop:
        - alertmanager
        - amtool
      ansible.builtin.copy:
        remote_src: true
        src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        owner: "alertmanager"
        group: "alertmanager"
        mode: "0755"

    - name: "Install | Clean up the downloads"
      ansible.builtin.file:
        path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64"
        state: absent

- name: "Install | Create a systemd service unit"
  notify: "(Re)start and enable Alertmanager"
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: "alertmanager"
    group: "alertmanager"
    mode: "0660"
