fail2ban_rhel_jail_sshd:
  enabled: "{{ fail2ban_rhel_jail_sshd_enabled }}"
  port: "{{ fail2ban_rhel_jail_sshd_port }}"
  findtime: "{{ fail2ban_rhel_jail_sshd_findtime }}"
  maxretry: "{{ fail2ban_rhel_jail_sshd_maxretry }}"
  bantime: "{{ fail2ban_rhel_jail_sshd_bantime }}"
  logpath: "{{ fail2ban_rhel_jail_sshd_logpath }}"
  backend: "{{ fail2ban_rhel_jail_sshd_backend }}"
  banaction: "{{ fail2ban_rhel_jail_sshd_banaction }}"
  ignoreips: "{{ fail2ban_rhel_jail_sshd_ignoreips }}"
