---
- name: Install agent configuration
  ansible.builtin.template:
    src: agent.ini.j2
    dest: /etc/slurm-web/agent.ini
    owner: "{{ slurm_web_user }}"
    group: "{{ slurm_web_group }}"
    mode: "0640"
  notify: Restart slurm-web-agent

- name: Install policy configuration
  ansible.builtin.template:
    src: policy.ini.j2
    dest: /etc/slurm-web/policy.ini
    owner: "{{ slurm_web_user }}"
    group: "{{ slurm_web_group }}"
    mode: "0640"
  notify: Restart slurm-web-agent

- name: Generate slurm-web JWT key
  ansible.builtin.command:
    cmd: slurm-web gen-jwt-key
    creates: /var/lib/slurm-web/jwt.key
  become_user: "{{ slurm_web_user }}"

- name: Copy Slurm JWT signing key for slurmrestd auth
  ansible.builtin.copy:
    src: "{{ slurm_jwt_key_src }}"
    dest: /var/lib/slurm-web/slurmrestd.key
    owner: "{{ slurm_web_user }}"
    group: "{{ slurm_web_group }}"
    mode: "0400"
    remote_src: "{{ slurm_jwt_key_remote | default(false) }}"
