---

- name: Enable EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Download Rackslab RPM GPG key
  ansible.builtin.get_url:
    url: https://pkgs.rackslab.io/keyring.asc
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-Rackslab
    mode: "0644"
  when: ansible_os_family == "RedHat"

- name: Create Rackslab DNF repository
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rackslab
    enabled: true
  loop:
    - name: rackslab
      description: Rackslab
      baseurl: "https://pkgs.rackslab.io/rpm/el{{ ansible_distribution_major_version }}/main/$basearch/"
    - name: rackslab-slurmweb-6
      description: Rackslab slurmweb-6
      baseurl: "https://pkgs.rackslab.io/rpm/el{{ ansible_distribution_major_version }}/slurmweb-6/$basearch/"
  when: ansible_os_family == "RedHat"

- name: Install slurm-web packages on RedHat
  ansible.builtin.dnf:
    name:
      - slurm-web-agent
      - slurm-web-gateway
    state: present
  when: ansible_os_family == "RedHat"

- name: Download Rackslab APT signing key
  ansible.builtin.shell:
    cmd: "curl -sS https://pkgs.rackslab.io/keyring.asc | gpg --dearmor | tee /usr/share/keyrings/rackslab.gpg > /dev/null"
    creates: /usr/share/keyrings/rackslab.gpg
  when: ansible_os_family == "Debian"

- name: Create Rackslab APT repository
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: https://pkgs.rackslab.io/deb
      Suites: {{ ansible_distribution_release }}
      Components: main slurmweb-6
      Architectures: amd64
      Signed-By: /usr/share/keyrings/rackslab.gpg
    dest: /etc/apt/sources.list.d/rackslab.sources
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == "Debian"

- name: Install slurm-web packages on Debian
  ansible.builtin.apt:
    name:
      - slurm-web-agent
      - slurm-web-gateway
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"