---
galaxy_info:
  role_name: miniforge
  namespace: genlab
  author: Alexander Gorelyshev
  company: Genlab, LLC
  description: Deploy the Miniforge distribution of the Mamba package manager
  license: MIT
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
