---
- name: "Install unzip package (Debian/Ubuntu)"
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: unzip
    state: present
    cache_valid_time: 3600

- name: "Install unzip package (RHEL/CentOS)"
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name: unzip
    state: present

- name: "Create a Loki system user"
  ansible.builtin.user:
    name: loki
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: "Create Loki system directories"
  with_items:
    - {path: "{{ loki_installation_path }}", mode: "0755"}
    - {path: "/etc/loki", mode: "0755"}
    - {path: "{{ loki_storage_path }}", mode: "0750"}
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: loki
    group: loki
    mode: "{{ item.mode }}"

- name: "Read installed Loki version"
  register: loki_version_check
  changed_when: false
  failed_when: false
  ansible.builtin.command:
    argv:
      - "{{ loki_installation_path }}/loki"
      - "-version"

- name: "Set Loki installation requirement"
  ansible.builtin.set_fact:
    loki_install_required: >-
      {{
        loki_version_check.rc != 0
        or loki_version not in loki_version_check.stdout
      }}

- name: "Install requested Loki version"
  when: loki_install_required
  block:
    - name: "Install Loki {{ loki_version }}"
      retries: 3
      delay: 1
      notify: "Restart-enable the Loki daemon"
      ansible.builtin.unarchive:
        src: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
        dest: /opt/loki/
        remote_src: true

    - name: "Rename and set permissions for the Loki binary"
      ansible.builtin.copy:
        src: "{{ loki_installation_path }}/loki-linux-amd64"
        dest: "{{ loki_installation_path }}/loki"
        owner: loki
        group: loki
        mode: "0755"
        remote_src: true

    - name: "Install companion Logcli {{ loki_version }}"
      when: loki_install_logcli
      retries: 3
      delay: 1
      ansible.builtin.unarchive:
        src: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/logcli-linux-amd64.zip"
        dest: /usr/local/bin
        remote_src: true

    - name: "Rename and set permissions for the Logcli binary"
      when: loki_install_logcli
      ansible.builtin.copy:
        src: "/usr/local/bin/logcli-linux-amd64"
        dest: "/usr/local/bin/logcli"
        owner: loki
        group: loki
        mode: "0755"
        remote_src: true

    - name: "Cleanup downloaded files"
      loop:
        - "{{ loki_installation_path }}/loki-linux-amd64"
        - "/usr/local/bin/logcli-linux-amd64"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent

- name: "Template Loki config file"
  notify: "Restart-enable the Loki daemon"
  ansible.builtin.template:
    src: "loki.yml.j2"
    dest: "/etc/loki/loki.yml"
    owner: loki
    group: loki
    mode: "0644"
    validate: "{{ loki_installation_path }}/loki -config.file=%s -verify-config"

- name: "Template the systemd unit file"
  notify: "Restart-enable the Loki daemon"
  ansible.builtin.template:
    src: templates/loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: "0644"

- name: "Ensure Loki is enabled and started"
  ansible.builtin.systemd_service:
    name: loki
    state: started
    daemon_reload: true
    enabled: true
