---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted

- name: Reload slurmdbd
  ansible.builtin.service:
    name: slurmdbd
    state: reloaded

- name: Restart slurmdbd
  ansible.builtin.service:
    name: slurmdbd
    state: restarted

- name: Reload slurmctld
  ansible.builtin.service:
    name: slurmctld
    state: reloaded

- name: Restart slurmctld
  ansible.builtin.service:
    name: slurmctld
    state: restarted

- name: Reload slurmd
  ansible.builtin.service:
    name: slurmd
    state: reloaded

- name: Restart slurmd
  ansible.builtin.service:
    name: slurmd
    state: restarted

- name: Reconfigure slurmctld
  ansible.builtin.command: scontrol reconfigure
  changed_when: true

- name: Restart slurmrestd
  ansible.builtin.service:
    name: slurmrestd
    state: restarted
