---
galaxy_info:
  role_name: fail2ban_rhel
  namespace: genlab
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: "Deploy a lean Fail2Ban configuration for RHEL/Rocky 9+ hosts"
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "EL"
      versions: ["9"]
    - name: "Rocky"
      versions: ["9.2"]

  galaxy_tags: []

dependencies: []
