client
dev tun
proto udp
remote {{ ovpn_client_remote.ip }} {{ ovpn_client_remote.port }}
resolv-retry infinite
nobind
persist-key
persist-tun

dhcp-option DNS {{ ovpn_client_remote.ip_dns }}
dhcp-option DOMAIN {{ ovpn_client_remote.domain }}

script-security 2
up /etc/openvpn/update-systemd-resolved
down /etc/openvpn/update-systemd-resolved
down-pre

<ca>
-----BEGIN CERTIFICATE-----
// certificate
-----END CERTIFICATE-----
</ca>
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
// static key
-----END OpenVPN Static key V1-----
</tls-auth>
remote-cert-tls server
key-direction 1
auth-user-pass {{ ovpn_client_auth_path }}
auth-retry nointeract
auth SHA512

cipher AES-256-GCM
tls-version-min 1.2

verb 3	