---
- name: Verify
  hosts: all
  gather_facts: false
  pre_tasks:
    # https://github.com/ansible/molecule/issues/3587#issuecomment-1158650179
    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: ['yml']

  tasks:
    - name: "Wait for Caddy to start and listen on the configured port"
      ansible.builtin.wait_for:
        port: 8080
        delay: 2
        timeout: 10

    # kics-scan ignore-block - kics doesn't like HTTP but on localhost it's not important
    - name: "Get the Caddy daemon response"
      retries: 3
      delay: 1
      register: caddy_response
      ansible.builtin.uri:
        url: "http://localhost:8080"
        return_content: true

    - name: "Assert Caddy is responding corectly"
      ansible.builtin.assert:
        that:
          - caddy_response.status == 200
          - "caddy_response.content == 'caddy-ok'"
        success_msg: "OK: HTTP {{ caddy_response.status }}, '{{ caddy_response.content }}'"
        fail_msg: "FAIL: HTTP {{ caddy_response.status }}, '{{ caddy_response.content }}'"
