---
make_lv_size: 100%FREE
make_lv_fs_type: ext4
make_lv_storage_mountpoint: "/mnt"
make_lv_storage_mountpoint_mode: "0775"
make_lv_mountpoint_owner: root
make_lv_mountpoint_group: root
make_lv_is_container: false
