---
- name: Converge
  hosts: all
  roles:
    - role: genlab.common.docker_ubuntu

    - role: genlab.common.samba_crazymax
      config: files/config.yml
      secrets: files/secrets.yml
      samba_crazymax_subnet: 10.0.0.0/24
      path_storage: /mnt/storage
