---
- name: "Install | install OpenSSH server (RHEL flavours)"
  when: ansible_os_family == "RHEL"
  ansible.builtin.dnf:
    name: openssh-server
    state: installed

- name: "Install | install OpenSSH server (Debian flavours)"
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: openssh-server
    state: present
    update_cache: true
