---
name: kics

on:
  pull_request:
    
jobs:
  kics:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        name: Check out source code

      - name: run a KICS scan
        uses: checkmarx/kics-github-action@83e3fc0659ba2ca4907bf765d050871cbb8a0a14
        with:
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
